-- Close the PostgREST grant hole on the public schema (2026-09-16). Generated by
-- scripts/audit_grants.py --emit; one plain statement per object, nothing dynamic.
--
-- Supabase's default ACL grants every object postgres creates in public to anon and
-- authenticated. Tables were saved by RLS; VIEWS run with their owner's rights and were
-- readable with the publishable key (v_sales with customer names, v_catalog_cost, stock,
-- margins). Three tables had no RLS and were writable. See the header of audit_grants.py
-- for why revoking is safe. Rollback = GRANT the same privileges back (do not).
--
-- Apply:  python -m scripts.apply_sql scripts/hotfix_view_grants_migration.sql
-- Verify: python -m scripts.audit_grants   (exit 0 = nothing exposed)

-- 1. Row-level security on every table (idempotent; service role bypasses RLS). Where the
--    assistant's yq_readonly role holds a SELECT grant, keep its read via a policy, mirroring
--    the existing *_yq_readonly_read pattern from scripts/security_migration.sql.
alter table public."agent_events" enable row level security;
alter table public."agent_runs" enable row level security;
alter table public."agent_schedules" enable row level security;
alter table public."app_invites" enable row level security;
alter table public."app_settings" enable row level security;
alter table public."ar_ageing" enable row level security;
alter table public."audit_log" enable row level security;
alter table public."catalog_items" enable row level security;
alter table public."catalog_stock_map" enable row level security;
alter table public."catalog_visits" enable row level security;
alter table public."categories" enable row level security;
alter table public."chat_uploads" enable row level security;
alter table public."customer_aliases" enable row level security;
alter table public."customer_contacts" enable row level security;
alter table public."customers" enable row level security;
alter table public."discount_rules" enable row level security;
alter table public."division_rules" enable row level security;
alter table public."field_notes" enable row level security;
alter table public."ingest_runs" enable row level security;
alter table public."kb_chunks" enable row level security;
alter table public."lead_events" enable row level security;
alter table public."leads" enable row level security;
alter table public."ledger_entries" enable row level security;
alter table public."marketing_opt_outs" enable row level security;
alter table public."mrn_landed_costs" enable row level security;
alter table public."mrn_lines" enable row level security;
alter table public."order_files" enable row level security;
alter table public."order_lines" enable row level security;
alter table public."orders" enable row level security;
alter table public."outreach_queue" enable row level security;
alter table public."outreach_touches" enable row level security;
alter table public."pending_actions" enable row level security;
alter table public."procurement_events" enable row level security;
alter table public."procurement_orders" enable row level security;
alter table public."product_aliases" enable row level security;
alter table public."product_finds" enable row level security;
alter table public."product_profitability" enable row level security;
alter table public."products" enable row level security;
alter table public."purchase_costs" enable row level security;
alter table public."purchase_orders" enable row level security;
alter table public."query_cache" enable row level security;
alter table public."salesman_channels" enable row level security;
alter table public."salesman_targets" enable row level security;
alter table public."salesmen" enable row level security;
alter table public."selling_prices" enable row level security;
alter table public."shop_counters" enable row level security;
alter table public."shop_events" enable row level security;
alter table public."shop_order_events" enable row level security;
alter table public."shop_order_lines" enable row level security;
alter table public."shop_orders" enable row level security;
alter table public."social_posts" enable row level security;
alter table public."stock_balance" enable row level security;
alter table public."stock_movements" enable row level security;
alter table public."supplier_prices" enable row level security;
alter table public."user_roles" enable row level security;
alter table public."wa_messages" enable row level security;
alter table public."wa_sessions" enable row level security;
drop policy if exists "app_settings_yq_readonly_read" on public."app_settings";
create policy "app_settings_yq_readonly_read" on public."app_settings" for select to yq_readonly using (true);
drop policy if exists "catalog_items_yq_readonly_read" on public."catalog_items";
create policy "catalog_items_yq_readonly_read" on public."catalog_items" for select to yq_readonly using (true);
drop policy if exists "categories_yq_readonly_read" on public."categories";
create policy "categories_yq_readonly_read" on public."categories" for select to yq_readonly using (true);
drop policy if exists "customer_aliases_yq_readonly_read" on public."customer_aliases";
create policy "customer_aliases_yq_readonly_read" on public."customer_aliases" for select to yq_readonly using (true);
drop policy if exists "customer_contacts_yq_readonly_read" on public."customer_contacts";
create policy "customer_contacts_yq_readonly_read" on public."customer_contacts" for select to yq_readonly using (true);
drop policy if exists "division_rules_yq_readonly_read" on public."division_rules";
create policy "division_rules_yq_readonly_read" on public."division_rules" for select to yq_readonly using (true);
drop policy if exists "leads_yq_readonly_read" on public."leads";
create policy "leads_yq_readonly_read" on public."leads" for select to yq_readonly using (true);
drop policy if exists "mrn_landed_costs_yq_readonly_read" on public."mrn_landed_costs";
create policy "mrn_landed_costs_yq_readonly_read" on public."mrn_landed_costs" for select to yq_readonly using (true);
drop policy if exists "mrn_lines_yq_readonly_read" on public."mrn_lines";
create policy "mrn_lines_yq_readonly_read" on public."mrn_lines" for select to yq_readonly using (true);
drop policy if exists "order_files_yq_readonly_read" on public."order_files";
create policy "order_files_yq_readonly_read" on public."order_files" for select to yq_readonly using (true);
drop policy if exists "procurement_events_yq_readonly_read" on public."procurement_events";
create policy "procurement_events_yq_readonly_read" on public."procurement_events" for select to yq_readonly using (true);
drop policy if exists "procurement_orders_yq_readonly_read" on public."procurement_orders";
create policy "procurement_orders_yq_readonly_read" on public."procurement_orders" for select to yq_readonly using (true);
drop policy if exists "product_finds_yq_readonly_read" on public."product_finds";
create policy "product_finds_yq_readonly_read" on public."product_finds" for select to yq_readonly using (true);
drop policy if exists "products_yq_readonly_read" on public."products";
create policy "products_yq_readonly_read" on public."products" for select to yq_readonly using (true);
drop policy if exists "purchase_orders_yq_readonly_read" on public."purchase_orders";
create policy "purchase_orders_yq_readonly_read" on public."purchase_orders" for select to yq_readonly using (true);
drop policy if exists "salesman_channels_yq_readonly_read" on public."salesman_channels";
create policy "salesman_channels_yq_readonly_read" on public."salesman_channels" for select to yq_readonly using (true);
drop policy if exists "salesman_targets_yq_readonly_read" on public."salesman_targets";
create policy "salesman_targets_yq_readonly_read" on public."salesman_targets" for select to yq_readonly using (true);
drop policy if exists "selling_prices_yq_readonly_read" on public."selling_prices";
create policy "selling_prices_yq_readonly_read" on public."selling_prices" for select to yq_readonly using (true);
drop policy if exists "stock_balance_yq_readonly_read" on public."stock_balance";
create policy "stock_balance_yq_readonly_read" on public."stock_balance" for select to yq_readonly using (true);
drop policy if exists "supplier_prices_yq_readonly_read" on public."supplier_prices";
create policy "supplier_prices_yq_readonly_read" on public."supplier_prices" for select to yq_readonly using (true);

-- 2. Views: revoke everything from the browser-facing roles.
revoke all on table public."shipments" from anon, authenticated;
revoke all on table public."v_basket_affinity" from anon, authenticated;
revoke all on table public."v_catalog" from anon, authenticated;
revoke all on table public."v_catalog_cost" from anon, authenticated;
revoke all on table public."v_catalog_pairs" from anon, authenticated;
revoke all on table public."v_catalog_stock" from anon, authenticated;
revoke all on table public."v_catalog_stock_rows" from anon, authenticated;
revoke all on table public."v_catalog_velocity" from anon, authenticated;
revoke all on table public."v_cost_change" from anon, authenticated;
revoke all on table public."v_current_stock" from anon, authenticated;
revoke all on table public."v_current_stock_agent" from anon, authenticated;
revoke all on table public."v_customer_ltv" from anon, authenticated;
revoke all on table public."v_division_summary" from anon, authenticated;
revoke all on table public."v_inventory_aging" from anon, authenticated;
revoke all on table public."v_item_division" from anon, authenticated;
revoke all on table public."v_item_velocity" from anon, authenticated;
revoke all on table public."v_landed_margin" from anon, authenticated;
revoke all on table public."v_lead_pipeline" from anon, authenticated;
revoke all on table public."v_lead_segments" from anon, authenticated;
revoke all on table public."v_low_stock" from anon, authenticated;
revoke all on table public."v_margin_leakage" from anon, authenticated;
revoke all on table public."v_marketing_kpis" from anon, authenticated;
revoke all on table public."v_month_pace" from anon, authenticated;
revoke all on table public."v_outreach_attribution" from anon, authenticated;
revoke all on table public."v_po_cost_change" from anon, authenticated;
revoke all on table public."v_po_item" from anon, authenticated;
revoke all on table public."v_po_price_history" from anon, authenticated;
revoke all on table public."v_price_change" from anon, authenticated;
revoke all on table public."v_price_history" from anon, authenticated;
revoke all on table public."v_price_list" from anon, authenticated;
revoke all on table public."v_price_list_by_book" from anon, authenticated;
revoke all on table public."v_price_tracker" from anon, authenticated;
revoke all on table public."v_procurement_board" from anon, authenticated;
revoke all on table public."v_product_economics" from anon, authenticated;
revoke all on table public."v_product_margin" from anon, authenticated;
revoke all on table public."v_purchase_history" from anon, authenticated;
revoke all on table public."v_purchase_lifecycle" from anon, authenticated;
revoke all on table public."v_purchase_price_events" from anon, authenticated;
revoke all on table public."v_receivables" from anon, authenticated;
revoke all on table public."v_return_rates" from anon, authenticated;
revoke all on table public."v_returns" from anon, authenticated;
revoke all on table public."v_sales" from anon, authenticated;
revoke all on table public."v_sales_agent" from anon, authenticated;
revoke all on table public."v_sales_by_category" from anon, authenticated;
revoke all on table public."v_sales_by_channel" from anon, authenticated;
revoke all on table public."v_sales_by_channel_agent" from anon, authenticated;
revoke all on table public."v_sales_by_division" from anon, authenticated;
revoke all on table public."v_sales_by_month_channel" from anon, authenticated;
revoke all on table public."v_sales_by_payment" from anon, authenticated;
revoke all on table public."v_sales_by_period" from anon, authenticated;
revoke all on table public."v_sales_by_period_agent" from anon, authenticated;
revoke all on table public."v_sales_by_salesman" from anon, authenticated;
revoke all on table public."v_sales_by_salesman_agent" from anon, authenticated;
revoke all on table public."v_salesman_stock_recon" from anon, authenticated;
revoke all on table public."v_shop_order_lines_agent" from anon, authenticated;
revoke all on table public."v_shop_orders_agent" from anon, authenticated;
revoke all on table public."v_shop_unpriced_stock" from anon, authenticated;
revoke all on table public."v_stock_daily_movement" from anon, authenticated;
revoke all on table public."v_stock_health" from anon, authenticated;
revoke all on table public."v_stock_health_agent" from anon, authenticated;
revoke all on table public."v_stock_transfers" from anon, authenticated;
revoke all on table public."v_supplier_price_history" from anon, authenticated;
revoke all on table public."v_top_customers" from anon, authenticated;
revoke all on table public."v_transfer_flow" from anon, authenticated;
revoke all on table public."v_vendor_scorecard" from anon, authenticated;

-- 3. Tables: same. RLS stays on; the API keeps its service-role access.
revoke all on table public."agent_events" from anon, authenticated;
revoke all on table public."agent_runs" from anon, authenticated;
revoke all on table public."agent_schedules" from anon, authenticated;
revoke all on table public."app_invites" from anon, authenticated;
revoke all on table public."app_settings" from anon, authenticated;
revoke all on table public."ar_ageing" from anon, authenticated;
revoke all on table public."audit_log" from anon, authenticated;
revoke all on table public."catalog_items" from anon, authenticated;
revoke all on table public."catalog_stock_map" from anon, authenticated;
revoke all on table public."catalog_visits" from anon, authenticated;
revoke all on table public."categories" from anon, authenticated;
revoke all on table public."chat_uploads" from anon, authenticated;
revoke all on table public."customer_aliases" from anon, authenticated;
revoke all on table public."customer_contacts" from anon, authenticated;
revoke all on table public."customers" from anon, authenticated;
revoke all on table public."discount_rules" from anon, authenticated;
revoke all on table public."division_rules" from anon, authenticated;
revoke all on table public."field_notes" from anon, authenticated;
revoke all on table public."ingest_runs" from anon, authenticated;
revoke all on table public."kb_chunks" from anon, authenticated;
revoke all on table public."lead_events" from anon, authenticated;
revoke all on table public."leads" from anon, authenticated;
revoke all on table public."ledger_entries" from anon, authenticated;
revoke all on table public."marketing_opt_outs" from anon, authenticated;
revoke all on table public."mrn_landed_costs" from anon, authenticated;
revoke all on table public."mrn_lines" from anon, authenticated;
revoke all on table public."order_files" from anon, authenticated;
revoke all on table public."order_lines" from anon, authenticated;
revoke all on table public."orders" from anon, authenticated;
revoke all on table public."outreach_queue" from anon, authenticated;
revoke all on table public."outreach_touches" from anon, authenticated;
revoke all on table public."pending_actions" from anon, authenticated;
revoke all on table public."procurement_events" from anon, authenticated;
revoke all on table public."procurement_orders" from anon, authenticated;
revoke all on table public."product_aliases" from anon, authenticated;
revoke all on table public."product_finds" from anon, authenticated;
revoke all on table public."product_profitability" from anon, authenticated;
revoke all on table public."products" from anon, authenticated;
revoke all on table public."purchase_costs" from anon, authenticated;
revoke all on table public."purchase_orders" from anon, authenticated;
revoke all on table public."query_cache" from anon, authenticated;
revoke all on table public."salesman_channels" from anon, authenticated;
revoke all on table public."salesman_targets" from anon, authenticated;
revoke all on table public."salesmen" from anon, authenticated;
revoke all on table public."selling_prices" from anon, authenticated;
revoke all on table public."shop_counters" from anon, authenticated;
revoke all on table public."shop_events" from anon, authenticated;
revoke all on table public."shop_order_events" from anon, authenticated;
revoke all on table public."shop_order_lines" from anon, authenticated;
revoke all on table public."shop_orders" from anon, authenticated;
revoke all on table public."social_posts" from anon, authenticated;
revoke all on table public."stock_balance" from anon, authenticated;
revoke all on table public."stock_movements" from anon, authenticated;
revoke all on table public."supplier_prices" from anon, authenticated;
revoke all on table public."user_roles" from anon, authenticated;
revoke all on table public."wa_messages" from anon, authenticated;
revoke all on table public."wa_sessions" from anon, authenticated;

-- 4. Sequences and postgres-owned functions.
revoke all on sequence public."agent_events_id_seq" from anon, authenticated;
revoke all on sequence public."agent_runs_id_seq" from anon, authenticated;
revoke all on sequence public."ar_ageing_id_seq" from anon, authenticated;
revoke all on sequence public."audit_log_id_seq" from anon, authenticated;
revoke all on sequence public."catalog_items_id_seq" from anon, authenticated;
revoke all on sequence public."catalog_visits_id_seq" from anon, authenticated;
revoke all on sequence public."categories_id_seq" from anon, authenticated;
revoke all on sequence public."customers_id_seq" from anon, authenticated;
revoke all on sequence public."discount_rules_id_seq" from anon, authenticated;
revoke all on sequence public."division_rules_id_seq" from anon, authenticated;
revoke all on sequence public."field_notes_id_seq" from anon, authenticated;
revoke all on sequence public."ingest_runs_id_seq" from anon, authenticated;
revoke all on sequence public."kb_chunks_id_seq" from anon, authenticated;
revoke all on sequence public."lead_events_id_seq" from anon, authenticated;
revoke all on sequence public."leads_id_seq" from anon, authenticated;
revoke all on sequence public."ledger_entries_id_seq" from anon, authenticated;
revoke all on sequence public."marketing_opt_outs_id_seq" from anon, authenticated;
revoke all on sequence public."mrn_landed_costs_id_seq" from anon, authenticated;
revoke all on sequence public."mrn_lines_id_seq" from anon, authenticated;
revoke all on sequence public."order_files_id_seq" from anon, authenticated;
revoke all on sequence public."order_lines_id_seq" from anon, authenticated;
revoke all on sequence public."orders_id_seq" from anon, authenticated;
revoke all on sequence public."outreach_queue_id_seq" from anon, authenticated;
revoke all on sequence public."outreach_touches_id_seq" from anon, authenticated;
revoke all on sequence public."pending_actions_id_seq" from anon, authenticated;
revoke all on sequence public."procurement_events_id_seq" from anon, authenticated;
revoke all on sequence public."procurement_orders_id_seq" from anon, authenticated;
revoke all on sequence public."product_aliases_id_seq" from anon, authenticated;
revoke all on sequence public."product_finds_id_seq" from anon, authenticated;
revoke all on sequence public."product_profitability_id_seq" from anon, authenticated;
revoke all on sequence public."products_id_seq" from anon, authenticated;
revoke all on sequence public."purchase_costs_id_seq" from anon, authenticated;
revoke all on sequence public."purchase_orders_id_seq" from anon, authenticated;
revoke all on sequence public."query_cache_id_seq" from anon, authenticated;
revoke all on sequence public."salesmen_id_seq" from anon, authenticated;
revoke all on sequence public."selling_prices_id_seq" from anon, authenticated;
revoke all on sequence public."shop_events_id_seq" from anon, authenticated;
revoke all on sequence public."shop_order_events_id_seq" from anon, authenticated;
revoke all on sequence public."shop_order_lines_id_seq" from anon, authenticated;
revoke all on sequence public."shop_orders_id_seq" from anon, authenticated;
revoke all on sequence public."social_posts_id_seq" from anon, authenticated;
revoke all on sequence public."stock_balance_id_seq" from anon, authenticated;
revoke all on sequence public."stock_movements_id_seq" from anon, authenticated;
revoke all on sequence public."supplier_prices_id_seq" from anon, authenticated;
revoke all on sequence public."user_roles_id_seq" from anon, authenticated;
revoke all on sequence public."wa_messages_id_seq" from anon, authenticated;
--    Postgres grants EXECUTE on new functions to PUBLIC, so revoking from anon alone changes
--    nothing: revoke from PUBLIC and hand it back only to the API's service role.
revoke execute on function public."match_kb"(query_text text, k integer, kinds text[]) from public, anon, authenticated;
grant execute on function public."match_kb"(query_text text, k integer, kinds text[]) to service_role;

-- 5. Stale blanket read policies for authenticated (inert once grants are gone).
drop policy if exists "app_settings_read" on public."app_settings";
drop policy if exists "ar_ageing_read" on public."ar_ageing";
drop policy if exists "catalog_items_read" on public."catalog_items";
drop policy if exists "customer_contacts_read" on public."customer_contacts";
drop policy if exists "salesman_targets_read" on public."salesman_targets";
drop policy if exists "stock_balance_read" on public."stock_balance";
drop policy if exists "user_roles_read" on public."user_roles";

-- 6. Stop the default ACL from re-granting future objects. Only the defaults owned by
--    postgres can be changed from this connection; objects created by supabase_admin
--    (extensions) keep theirs, which is why audit_grants.py must stay in the release check.
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema public revoke all on functions from anon, authenticated;

-- 7. The one thing the publishable key may still touch: an empty ping table for the
--    GitHub keepalive job (.github/workflows/keepalive.yml). RLS on, no policy -> [] + HTTP 200.
create table if not exists public.keepalive_ping (id smallint primary key);
alter table public.keepalive_ping enable row level security;
revoke all on table public.keepalive_ping from anon, authenticated;
grant select on table public.keepalive_ping to anon;

-- 8. Verification: fails the transaction if anything is still exposed.
do $$
declare
  leftover int;
  norls int;
  pol int;
begin
  select count(*) into leftover
  from information_schema.role_table_grants
  where table_schema = 'public' and grantee in ('anon', 'authenticated')
    and not (table_name = 'keepalive_ping' and grantee = 'anon' and privilege_type = 'SELECT');
  if leftover > 0 then
    raise exception 'grant lockdown FAILED: % anon/authenticated grants remain on public', leftover;
  end if;
  select count(*) into norls from pg_tables where schemaname = 'public' and not rowsecurity;
  if norls > 0 then
    raise exception 'grant lockdown FAILED: % public tables without RLS', norls;
  end if;
  select count(*) into pol from pg_policies where schemaname = 'public' and 'authenticated' = any(roles);
  if pol > 0 then
    raise exception 'grant lockdown FAILED: % policies still target authenticated', pol;
  end if;
  raise notice 'grant lockdown: verified -- public schema is closed to anon/authenticated (keepalive_ping SELECT only)';
end $$;
