/**
 * Every word the marketplace shows, in one place. English today; Arabic lands here later
 * without touching a component (plan §F: RTL readiness). Keep sentences short — most readers
 * are on a phone, in a shop, between customers.
 */
export const S = {
  brand: 'YQ Marketplace',
  company: 'YQ Bahrain',
  tagline: 'Mobile accessories · trade prices',
  nav: { home: 'Home', search: 'Search', cart: 'Cart', orders: 'Orders' },
  searchPlaceholder: 'Search cables, chargers, TWS…',
  searchLabel: 'Search the marketplace',
  categories: { all: 'All' },
  rails: {
    regulars: 'Order again',
    regularsCta: 'Review regular order',
    newSince: 'New since your last order',
    best: 'Best sellers',
    arrived: 'Just arrived',
    offers: 'On offer',
    complete: 'Complete your order',
    together: 'Often ordered together',
    seeAll: 'See all',
  },
  hero: { label: 'This week', cta: 'See deal', endsIn: 'Ends in' },
  rep: { yours: 'Your YQ representative', whatsapp: 'WhatsApp', tell: 'Tell' },
  welcome: (shop: string) => `Welcome back, ${shop}`,
  card: {
    add: 'Add',
    backorder: 'Backorder',
    soldOut: 'Sold out',
    tellRep: (first: string) => `Tell ${first}`,
    perPiece: 'per pc',
    min: (n: number) => `Minimum ${n} pcs`,
    tier: (n: number, price: string) => `${n}+ → ${price}`,
    nudge: (more: number, n: number) => `${more} more for the ${n}+ price`,
    volumePrices: 'Volume prices available',
  },
  qty: { title: 'Quantity', apply: 'Apply', presets: 'Quick pick', remove: 'Remove' },
  cart: {
    title: 'Your order',
    empty: 'Nothing in your order yet',
    emptyHint: 'Add a product and it will show up here.',
    browse: 'Browse products',
    note: 'Note for your representative',
    notePlaceholder: 'Delivery day, packing, anything else',
    coupon: 'Have a coupon?',
    couponPlaceholder: 'Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    place: 'Place order',
    placeHint: (first: string) => `${first} confirms price, stock and delivery.`,
    placeHintGeneric: 'A YQ representative confirms price, stock and delivery.',
    ask: (first: string) => `Ask ${first} on WhatsApp`,
    remove: 'Remove',
    updating: 'Updating…',
    each: 'each',
  },
  checkout: {
    title: 'Your details',
    phone: 'Phone',
    phoneHint: '8-digit Bahrain number, or international with +',
    phoneBad: 'Enter an 8-digit Bahrain number, or an international number starting with +.',
    shop: 'Shop name',
    name: 'Your name',
    nameBad: 'Please tell us your name.',
    area: 'Area',
    areaPlaceholder: 'Manama, Riffa…',
    email: 'Email (optional)',
    emailBad: 'That email address does not look right.',
    save: 'Save my details on this phone',
    haveRep: 'Already have a YQ representative?',
    chooseRep: 'Choose',
    noRep: 'No preference',
    place: 'Place order',
    connecting: 'Connecting to YQ…',
    sending: 'Sending…',
    failed: 'We could not send your order. Please check your connection and try again.',
    noPayment: 'No payment now — everything is confirmed with you first.',
  },
  placed: {
    title: 'Order received',
    sentTo: (first: string) => `Sent to ${first}`,
    unassigned: 'A YQ representative will confirm shortly.',
    number: 'Order number',
    next: ['Your representative confirms price and stock', 'Our warehouse prepares it', 'It is delivered to your shop'],
    whatsapp: (first: string) => `WhatsApp ${first}`,
    email: (first: string) => `Email ${first}`,
    track: 'Track order',
    install: 'Add YQ to your home screen',
    continue: 'Continue shopping',
    duplicate: 'This order was already received — here it is.',
  },
  track: {
    title: 'Your order',
    placed: 'Placed',
    expected: 'Expected',
    changes: 'Changes to your order',
    removedLine: 'not available this time',
    cancel: 'Cancel order',
    cancelConfirm: 'Cancel this order? Your representative will be told.',
    cancelWhy: 'Reason (optional)',
    cancelled: 'This order was cancelled.',
    cancelledHint: 'Talk to your representative if that was not expected.',
    reorder: 'Order again',
    items: 'Items',
    deliveringTo: 'Delivering to',
    timeline: 'Timeline',
    notFound: 'We could not find this order.',
    notFoundHint: 'Please ask your YQ representative for an up-to-date link.',
    message: (first: string) => `Message ${first} on WhatsApp`,
    refreshing: 'Checking for updates…',
  },
  orders: {
    title: 'My orders',
    empty: 'No orders on this phone yet',
    emptyHint: 'Orders you place here appear on this page, with live tracking.',
    thisPhone: 'Orders from this phone',
    otherPhone: 'Ordered from another phone? Ask your representative to send you your orders link.',
  },
  states: {
    loading: 'Loading the marketplace…',
    connecting: 'Connecting to YQ…',
    connectingHint: 'The server is waking up. This takes a moment the first time.',
    retry: 'Try again',
    offline: 'You are offline — showing the last catalog we saved on this phone.',
    closed: 'The marketplace is closed right now.',
    closedHint: 'Please ask your YQ representative for help.',
    noMatch: (q: string) => `No match for “${q}”`,
    noMatchHint: 'Try another word, a code, or one of these:',
    didYouMean: 'Did you mean',
    recent: 'Recent searches',
    clear: 'Clear',
    showMore: (n: number) => `Show more (${n} left)`,
    products: (n: number) => `${n} ${n === 1 ? 'product' : 'products'}`,
    pricesAsOf: (d: string) => `Prices ${d}`,
    stockAsOf: (d: string) => `Stock as of ${d}`,
    footer: 'YQ Bahrain W.L.L · Trade prices — may change without notice.',
  },
} as const
