/**
 * Every word the marketplace shows, in one place. English today; Arabic lands here later
 * without touching a component (`locale` flips `dir` on <html>). Keep sentences short — most
 * readers are on a phone, in a shop, between customers.
 */
export const locale: { lang: 'en' | 'ar'; dir: 'ltr' | 'rtl' } = { lang: 'en', dir: 'ltr' }

export const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`

export const S = {
  brand: 'YQ Marketplace',
  company: 'YQ Bahrain',
  tagline: 'Restock faster. Sell more.',
  kicker: 'Where Bahrain restocks.',
  nav: { home: 'Home', search: 'Search', me: 'My YQ', orders: 'Orders', quick: 'Quick order', restock: 'Restock', browse: 'Browse', deals: 'Deals', main: 'Main navigation', shortcuts: 'Shortcuts', inRestock: (n: number) => `${plural(n, 'product', 'products')} in your restock` },
  searchPlaceholder: 'Search or type a code…',
  searchLabel: 'Search the marketplace',
  categories: { title: 'Shop by category', browse: 'Browse categories' },
  home: {
    quick: 'Quick order',
    addAll: (n: number, total: string) => `Add all ${n} · ≈ ${total}`,
    editQty: 'Edit quantities',
    lastOrder: 'Your last order',
    regular: 'Your regular stock',
    viewed: 'Picked up again',
    offerEnds: (t: string) => `Ends in ${t}`,
    newCount: (n: number) => `${n} new`,
    all: 'All products',
    seeAll: 'See all',
    /** how many lines of a restock are running low — the continue card's summary line */
    fewLeftCount: (n: number) => `${plural(n, 'line', 'lines')} running low`,
    /** v3 home: the three wholesale actions under the category tiles */
    actions: 'Quick actions',
    pasteSub: 'Codes and quantities, the way you text them',
    againSub: (n: number) => `${plural(n, 'product', 'products')} from your last order`,
    askRep: 'Ask your rep',
    askSub: (name: string) => `${name} on WhatsApp`,
    /** v3 home: the paste-your-list card (no cart, no last order) */
    pasteTitle: 'Order the way you text',
    pasteLine: 'Paste your WhatsApp list — codes and quantities become lines you can check.',
    /** an example list, in the format the quick-order parser reads (see S.quick.pasteHint) */
    pasteExample: ['24 x C18', '12 UK15', 'tws 6'],
    /** accessible name of the grid/list toggle above All products */
    view: 'View',
  },
  rails: {
    /** no time span: the 'new' badge window is shop_new_days (30 by default, admin-editable) */
    arrived: 'New arrivals',
    together: 'Often ordered together',
    essentials: 'Restock essentials',
    fresh: 'New arrivals',
    moving: 'Moving fast in Bahrain',
    continue: 'Continue your restock',
    again: 'Order again',
  },
  deals: {
    title: 'Stock-Up Deals',
    lastChance: 'Last-Chance Stock',
    line: 'Lines we’re clearing · trade price · while stock lasts',
    /* the section line is picked from the sets that actually have lines — never promise a kind we have none of */
    /** real price-book drops AND lines we’re clearing */
    dealsLine: 'Real price drops and last-chance lines, at trade price.',
    /** real price-book drops only */
    dealsLineDrops: 'Real cuts in our price book — the old price is on every card.',
    /** live offers or bundles, plus lines we’re clearing */
    dealsLineMixed: 'Real deals from our price book, and lines we’re clearing — at trade price.',
    /** live offers or bundles only */
    dealsLineOffers: 'Live offers from our price book, at trade price.',
    all: 'All',
    drops: 'Price drops',
    last: 'Last chance',
    offers: 'Offers',
    bundles: 'Bundles',
    badge: 'Last chance',
    /** card badge for a real offer or price-book drop — never a clearing line */
    deal: 'Deal',
    retail: (price: string) => `Retail ${price}`,
    margin: (margin: string, pct: number) => `Your margin ${margin}/pc · ${pct}%`,
    high: 'High margin',
    count: (n: number) => plural(n, 'line', 'lines'),
    seeAll: 'See all deals',
  },
  brands: { title: 'Shop by brand', lines: (n: number) => plural(n, 'line', 'lines') },
  /** card badges (lib/format BADGE_META); a live offer reads S.deals.deal, a clearing line S.deals.badge */
  badges: { best: 'Best seller', fast: 'Selling fast', fresh: 'New', trending: 'Trending', drop: 'Price drop' },
  band: {
    title: 'Ready to restock?',
    line: 'Paste your list or reorder in one tap — delivered across Bahrain.',
    paste: 'Paste your list',
    again: 'Order again',
    browse: 'Browse essentials',
  },
  minimum: {
    requested: 'Sent as a small order request — your representative confirms it case by case.',
  },
  wholesale: {
    kicker: 'Wholesale order',
    away: (amount: string) => `${amount} away from your wholesale order`,
    progress: (have: string, need: string) => `${have} of ${need}`,
    ready: 'Wholesale order ready',
    readyHint: 'Your restock qualifies — check out when you’re ready.',
    fill: 'Complete your restock with these',
    closes: 'completes your order',
    keep: 'Keep restocking',
    checkout: 'Continue to checkout',
    small: 'Request a small order',
    review: 'Review restock',
    /** labels under the progress rail: the amount sits on its own line above each caption */
    inRestock: 'in your restock',
    minimumLabel: 'wholesale minimum',
    toGo: (amount: string) => `${amount} to go`,
    /** a gap-filler row: "12 × BHD 0.400 · BHD 4.800" */
    line: (qty: number, unit: string, value: string) => `${qty} × ${unit} · ${value}`,
    showMore: (n: number) => `Show ${n} more`,
  },
  small: {
    title: 'Small order request',
    body: (min: string) => `Orders under ${min} are reviewed by your YQ representative and confirmed on WhatsApp, case by case.`,
    fee: (fee: string) => `A small order may carry a ${fee} handling fee.`,
    noPayment: 'No payment now — nothing is sent until your representative confirms.',
    /** under the Send request button, BEFORE anything is sent (S.minimum.requested is the after) */
    sendHint: 'No payment now — your representative confirms this small order case by case.',
    continue: 'Continue to request',
    keep: 'Keep restocking instead',
    send: 'Send request',
    received: 'Small order request received',
    receivedHint: 'Your representative reviews small orders case by case and confirms on WhatsApp.',
    badge: 'Small order request',
  },
  splash: {
    brand: 'Restock faster. Sell more.',
    welcome: (shop: string) => `Welcome back, ${shop}`,
    refill: 'Refill my shelf',
    skip: 'Tap to continue',
    skipClick: 'Click or press Esc to continue',
    kicker: 'Where Bahrain restocks.',
  },
  campaign: {
    cta: 'See more',
    sponsored: (n: string) => (n ? `Sponsored · ${n}` : 'Sponsored'),
    /** kicker of a category page's composed banner (in-stock lines of that category) */
    categoryStock: (n: number) => `${plural(n, 'line', 'lines')} in stock`,
  },
  slides: {
    label: 'Promotions',
    again: 'Order again',
    againLine: (n: number) => `${plural(n, 'product', 'products')} from your last order — one tap to restock.`,
    againCta: 'Reorder',
    last: 'Last-Chance Stock',
    lastLine: (n: number) => `${plural(n, 'line', 'lines')} we’re clearing — trade price while stock lasts.`,
    lastCta: 'See last-chance stock',
    /* no time span: the drop window is the admin's shop_price_drop_days (30 by default), not a month */
    drops: (n: number) => `${plural(n, 'price', 'prices')} cut in our price book`,
    dropsLine: 'Real cuts in our price book — the old price is on every card.',
    dropsCta: 'See price drops',
    essentials: 'Restock essentials',
    essentialsLine: 'The lines Bahrain shops reorder most.',
    essentialsCta: 'Restock now',
    fresh: 'New arrivals',
    freshLine: (n: number) => `${plural(n, 'new line', 'new lines')} on the shelf.`,
    freshCta: 'See what’s new',
    moving: 'Moving fast in Bahrain',
    movingLine: 'What shops are restocking right now.',
    movingCta: 'See what’s moving',
    quick: 'Paste your WhatsApp list',
    quickLine: 'We turn it into a wholesale order in seconds.',
    quickCta: 'Paste a list',
    prev: 'Previous slide',
    next: 'Next slide',
    go: (i: number, n: number) => `Slide ${i} of ${n}`,
    pause: 'Pause slideshow',
    play: 'Play slideshow',
    /** the round sticker on the New arrivals slide (words only, never a number) */
    stickerNew: 'New',
  },
  promise: { title: 'The YQ promise', app: 'Add YQ app' },
  spot: {
    title: 'Right now at YQ',
    popular: 'Popular right now',
    clearance: (n: number) => `${plural(n, 'last-chance line', 'last-chance lines')} at trade price`,
    drops: (n: number) => `${plural(n, 'price drop', 'price drops')} on this shelf`,
    arrived: (n: number) => `${plural(n, 'new line', 'new lines')} on the shelf`,
    prev: 'Previous',
    next: 'Next',
    slide: (i: number, n: number) => `Slide ${i} of ${n}`,
  },
  rep: { yours: 'Your YQ representative', whatsapp: 'WhatsApp', soon: 'Order once and your representative appears here.', default: 'YQ sales representative' },
  card: {
    add: 'Add',
    added: 'Added',
    backorder: 'Backorder',
    soldOut: 'Sold out',
    tellRep: (first: string) => `Tell ${first}`,
    askYq: 'Ask YQ',
    tellBack: 'Tell me when back',
    saveItem: 'Save',
    savedItem: 'Saved',
    zoom: 'Zoom photo',
    shareProduct: 'Share this product',
    tellBackDone: 'We will tell you when it is back',
    min: (n: number) => `Min ${n}`,
    packs: (n: number) => `packs of ${n}`,
    tier: (n: number, price: string) => `${n}+ → ${price}`,
    breaks: (n: number) => `${n} price breaks`,
    nudge: (more: number, price: string) => `${more} more → ${price} each`,
    volumePrices: 'Volume prices available',
    quickView: 'Quick view',
    grid: 'Grid',
    list: 'List',
    undo: 'Undo',
    removed: (name: string) => `${name} removed`,
    was: 'Was',
    priceOnRequest: 'Price on request',
    perPc: '/pc',
    stockIn: 'In stock',
    stockLow: 'Only a few left',
    stockOut: 'Out of stock',
    /** narrow cards: "Retail 2.200" (S.deals.retail) then this, e.g. "41% margin" — a share of retail */
    marginPct: (pct: number) => `${pct}% margin`,
    pcsPlus: (n: number) => `${n}+ pcs`,
    minPcs: (n: number) => `Min ${n} pcs`,
    tellBackText: (first: string, code: string, name: string) => `Hello${first ? ` ${first}` : ''}, please tell me when ${code} (${name}) is back in stock.`,
    backorderNote: 'Out of stock — order now and your representative confirms the date.',
    linkCopied: 'Link copied — paste it into WhatsApp',
    breaksCaption: 'Quantity price breaks',
    colQty: 'Quantity',
    colEach: 'Price each',
    details: 'Details',
    photo: 'Photo',
    viewProduct: 'Product',
    viewPackage: 'Package',
    photoSoon: 'Photo coming soon',
    scrollBack: 'Scroll back',
    scrollForward: 'Scroll forward',
  },
  qty: { title: 'Quantity', apply: 'Apply', presets: 'Quick pick', remove: 'Remove', tooMany: 'Too many — please ask your representative.' },
  shop: {
    saved: 'Saved',
    title: 'Browse',
    products: (n: number) => plural(n, 'product', 'products'),
    sort: 'Sort',
    shelf: 'Shelf order',
    popular: 'Popular',
    priceUp: 'Price: low to high',
    priceDown: 'Price: high to low',
    inStock: 'In stock',
    /** the `offers` chip: live offers only (on_offer), never a retail anchor */
    offers: 'Offers',
    new: 'New',
    clearance: 'Last chance',
    drops: 'Price drops',
    clear: 'Clear',
    filters: 'Filters',
    /** v3 browse: the chips row (sticky under the phone search band) */
    deals: 'Deals',
    essentials: 'Essentials',
    moving: 'Moving fast',
    view: 'View',
    /** the sort chip shows the active order; "Sort" while it is the shelf order */
    lowest: 'Lowest price',
    highest: 'Highest price',
    paste: 'Paste a list',
    none: 'Nothing on this shelf matches',
    noneHint: 'Clear a filter, or try another category.',
    savedNone: 'Tap the heart on a product and it waits for you here.',
    /** the "ask your rep" WhatsApp text when a search finds nothing */
    askHave: (first: string, q: string) => `Hello${first ? ` ${first}` : ''}, do you have “${q}” for my shop?`,
    notOnShelf: (q: string) => `“${q}” isn’t on our shelf`,
    notOnShelfHint: 'Try a code or another word — or ask your representative, who knows the warehouse.',
    removeFilter: (label: string) => `Remove filter: ${label}`,
  },
  search: {
    submit: 'Search',
    codeHint: 'Type a code like UK15 — Enter adds it',
    recent: 'Recent searches',
    codes: 'Codes',
    products: 'Products',
    categories: 'Categories',
    palette: 'Search products',
    keys: 'Enter opens · ⇧Enter adds · ↑↓ move',
    shortcut: '⌘K',
    preparing: 'Preparing search…',
    hints: ['Type-C cable', '20W charger', 'TWS earbuds', 'iPhone cable', 'Car charger', 'Power bank'],
    hintLead: 'Search',
    band: 'Search products or codes',
    popularRestocks: 'Popular restocks',
    /** the rotating example after hintLead: Search “20W charger” */
    hintQuoted: (hint: string) => `“${hint}”`,
  },
  quick: {
    title: 'Quick order',
    intro: 'Paste your WhatsApp list or type codes — it becomes a wholesale order you can check line by line.',
    paste: 'Paste your WhatsApp list',
    pasteHint: 'Codes and quantities, the way you text them — e.g. 24 x C18, 12 UK15, tws 6',
    pasteApply: 'Turn into lines',
    row: 'Code or product name…',
    addAll: (n: number) => `Add ${plural(n, 'line', 'lines')} to restock`,
    notFound: 'Not found — pick one',
    lists: 'Restock list',
    saveList: 'Save as a restock list',
    listName: 'List name',
    empty: 'Type a code or a product name — or paste the list you would send on WhatsApp.',
    remove: 'Remove row',
    /** v3: copy that used to be hard-coded in QuickOrderPage */
    lastOrderShort: (d: string) => `Your last order · ${d}`,
    addLine: 'Add a line',
    deleteList: (name: string) => `Delete ${name}`,
    unresolved: (n: number) => `${plural(n, 'line', 'lines')} not found — pick one`,
    listSaved: (name: string) => `Restock list saved: ${name}`,
    pastePlaceholder: '24 x C18\n12 UK15\ntws 6',
    listPlaceholder: 'Weekly cables',
  },
  restock: {
    title: 'Your restock',
    empty: 'Your restock list is empty',
    emptyHint: 'Add stock from the shelf, reorder, or paste your list.',
    browse: 'Browse essentials',
    again: 'Order again',
    paste: 'Paste a list',
    saved: 'Saved items',
    regular: 'Your regular stock',
    lines: 'In this restock',
    review: 'Review restock',
    more: 'Add to this restock',
    essentials: 'Restock essentials',
    againLine: (n: number, date?: string | null) => (date ? `Your last order · ${date} · ${plural(n, 'product', 'products')}` : `Your last order · ${plural(n, 'product', 'products')}`),
    addAll: (n: number, total: string) => `Add all ${n} · ≈ ${total}`,
    edit: 'Edit quantities',
    pasteHint: 'Type or paste codes from WhatsApp — they become lines in seconds.',
  },
  cart: {
    title: 'Your restock',
    summary: (i: number, u: number) => `${plural(i, 'product', 'products')} · ${u} pcs`,
    browse: 'Browse essentials',
    note: 'Note for your representative',
    noteFor: (first: string) => `Note for ${first}`,
    notePlaceholder: 'Delivery day, packing, anything else',
    coupon: 'Have a coupon?',
    couponPlaceholder: 'Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    place: 'Place wholesale order',
    review: 'Review restock',
    placeHint: (first: string) => `${first} confirms price, stock and delivery.`,
    placeHintGeneric: 'A YQ representative confirms price, stock and delivery.',
    ask: (first: string) => `Ask ${first} on WhatsApp`,
    remove: 'Remove',
    updating: 'Updating…',
    each: 'each',
    edit: 'Edit',
    mini: 'Your restock',
    full: 'View full restock',
    unlocked: 'Free delivery unlocked',
    keepShopping: 'Keep restocking',
    emptyMini: 'Your restock is empty',
    emptyMiniHint: 'Add stock from the shelf, or load your last order.',
    blocked: 'This order cannot be sent yet.',
    discount: 'Discount',
    askMessage: (first: string) => `Hello ${first}, a question about my order:`,
  },
  checkout: {
    title: 'Your details',
    phone: 'Phone',
    phoneHint: '8-digit Bahrain number, or international with +',
    phoneBad: 'Enter an 8-digit Bahrain number, or an international number starting with +.',
    shop: 'Shop name',
    name: 'Your name',
    nameBad: 'Please tell us your name.',
    area: 'Area',
    areaPlaceholder: 'Manama, Riffa…',
    other: 'Other',
    email: 'Email (optional)',
    emailBad: 'That email address does not look right.',
    more: 'More',
    save: 'Save my details on this phone',
    haveRep: 'Already have a YQ representative?',
    chooseRep: 'Choose',
    noRep: 'No preference',
    place: 'Place wholesale order',
    connecting: 'Connecting to YQ…',
    sending: 'Sending…',
    failed: 'We could not send your order. Please check your connection and try again.',
    noPayment: 'No payment now — everything is confirmed with you first.',
    deliveryLabel: 'Delivery',
    deliveryOptions: ['Next visit', 'As soon as possible', 'A specific day'],
    deliveryHint: 'Your representative confirms the day with you.',
    how: 'How it works',
    moreLines: (n: number) => `+${n} more`,
    reassure: (first: string) => `No payment now — ${first} confirms price, stock and delivery.`,
    welcomeBack: (shop: string) => `Welcome back, ${shop}`,
    welcomeBackHint: 'We filled in your shop from your last order — check and place it.',
  },
  placed: {
    title: 'Wholesale order received',
    sentTo: (first: string) => `Sent to ${first}`,
    unassigned: 'A YQ representative will confirm shortly.',
    number: 'Order number',
    next: ['Your representative confirms price and stock', 'Our warehouse prepares it', 'It is delivered to your shop'],
    whatsapp: (first: string) => `WhatsApp ${first}`,
    email: (first: string) => `Email ${first}`,
    track: 'Track order',
    install: 'Add YQ to your home screen',
    continue: 'Keep restocking',
    duplicate: 'This order was already received — here it is.',
    copy: 'Copy summary',
    copied: 'Copied',
    share: 'Share',
  },
  track: {
    title: 'Your order',
    placed: 'Placed',
    expected: 'Expected',
    changes: 'Changes to your order',
    removedLine: 'not available this time',
    cancel: 'Cancel order',
    cancelConfirm: 'Cancel this order? Your representative will be told.',
    cancelWhy: 'Reason (optional)',
    keep: 'Keep order',
    cancelled: 'This order was cancelled.',
    cancelledHint: 'Talk to your representative if that was not expected.',
    reorder: 'Order again',
    items: 'Items',
    deliveringTo: 'Delivering to',
    notFound: 'We could not find this order.',
    notFoundHint: 'Please ask your YQ representative for an up-to-date link.',
    message: (first: string) => `Message ${first} about this order`,
    forget: 'Remove from my orders',
    confirmed: '(confirmed)',
    order: (no: string) => `Order ${no}`,
    progress: 'Order progress',
    cancelFailed: 'Could not cancel — please message your representative.',
    copyFailed: 'Could not copy',
    sendWhatsapp: 'Send on WhatsApp',
    aboutOrder: (first: string, no: string) => `Hello ${first}, about my order ${no}:`,
  },
  orders: {
    title: 'My orders',
    empty: 'No orders on this phone yet',
    emptyHint: 'Orders you place here appear on this page, with live tracking.',
    thisPhone: 'Orders from this phone',
    otherPhone: 'Ordered from another phone? Ask your representative to send you your orders link.',
    all: 'All orders',
  },
  me: {
    title: 'My YQ',
    hello: 'Welcome back',
    hi: 'Welcome to YQ',
    quick: 'Quick actions',
    orders: 'Your orders',
    details: 'Your shop details',
    noDetails: 'Nothing saved yet — your shop details stay on this phone after your first wholesale order.',
    edit: 'Edit',
    done: 'Done',
    forget: 'Forget on this phone',
    forgotten: 'Your details were removed from this phone.',
    install: 'Add YQ to your home screen',
    installHint: 'Opens like an app — one tap from your home screen.',
    installIos: 'In Safari: Share → Add to Home Screen',
    language: 'Language',
    soon: 'Soon',
    about: 'About YQ',
    contact: 'Contact',
    clear: 'Clear this phone’s memory',
    clearConfirm: 'Forget saved details, quantities and searches on this phone?',
    cleared: 'This phone forgot everything.',
    version: 'Version',
    track: 'Track order',
    saved: 'Saved items',
    savedEmpty: 'Tap the heart on a product to keep it here — then restock it in one tap.',
    addAllSaved: (n: number) => `Add all ${n}`,
    ask: 'Ask YQ',
    askHint: 'Stock, prices, delivery — ask on WhatsApp',
    /** v3 merchant hub */
    hub: 'Your shop on YQ',
    again: 'Order again',
    paste: 'Paste a list',
    help: 'Help & how it works',
  },
  about: {
    title: 'About & help',
    company: 'YQ Bahrain W.L.L · Mobile accessories wholesale · Kingdom of Bahrain.',
    delivery: 'Delivery & returns',
    deliveryFree: 'Delivery across Bahrain is free.',
    deliveryOver: (t: string) => `Delivery across Bahrain is free on orders over BHD ${t}.`,
    deliveryHow: 'Your representative confirms every order first — price, stock and the delivery day — then our warehouse prepares it and it comes to your shop.',
    returns: 'Wrong or faulty items: tell your representative on the delivery day and they are swapped or credited on the next visit.',
    privacy: 'Privacy',
    privacyText: 'No account, no password. Your details, quantities and searches stay on this phone so ordering is fast; an order sends only what is needed to deliver it.',
    privacyForget: 'You can forget everything from My YQ at any time.',
    trade: 'Trade prices',
    tradeText: 'Prices on YQ are trade prices for shops and businesses, straight from our price book.',
    minimum: (min: string) => `Wholesale orders start at ${min}. Smaller orders can be sent as a request — your representative confirms them case by case.`,
    how: 'How ordering works',
    /** v3 about page */
    intro: 'Mobile accessories wholesale for shops across Bahrain — trade prices, live warehouse stock, and a representative who knows your shop.',
    onPage: 'On this page',
    contact: 'Contact',
    tradeConfirm: 'Your representative confirms the price of every line before your order is delivered.',
    minimumBlock: (min: string) => `Wholesale orders start at ${min}.`,
    minimumAllow: (min: string) => `Wholesale orders start at ${min}; smaller orders are accepted too.`,
    deliveryFee: (fee: string) => `Delivery across Bahrain is ${fee} per order.`,
    steps: [
      'Add stock from the shelf, reorder, or paste your WhatsApp list.',
      'Place your wholesale order — no payment now.',
      'Your representative confirms price, stock and the delivery day.',
      'Our warehouse prepares it and it comes to your shop.',
    ],
    step: (n: number) => `Step ${n}`,
  },
  footer: {
    tagline: 'Restock faster. Sell more.',
    company: 'YQ Bahrain W.L.L',
    what: 'Mobile accessories wholesale · Kingdom of Bahrain',
    help: 'Help',
    about: 'About YQ',
    delivery: 'Delivery & returns',
    privacy: 'Privacy',
    rep: 'Your representative',
    trade: 'Trade prices may change without notice.',
    tradeLink: 'Trade prices',
    how: 'How ordering works',
    priceBook: 'Price book',
    noRep: 'Place your first order and your YQ representative shows up here.',
  },
  states: {
    loading: 'Loading the marketplace…',
    connecting: 'Connecting to YQ…',
    connectingHint: 'The server is waking up. This takes a moment the first time.',
    couldNot: 'We could not reach YQ',
    couldNotHint: 'Check your connection and try again.',
    retry: 'Try again',
    offline: 'You are offline — showing the last catalog we saved on this phone.',
    closed: 'The marketplace is closed right now.',
    closedHint: 'Please ask your YQ representative for help.',
    noMatch: (q: string) => `No match for “${q}”`,
    noMatchHint: 'Try another word, a code, or one of these:',
    didYouMean: 'Did you mean',
    clear: 'Clear',
    showMore: (n: number) => `Show more (${n} left)`,
    products: (n: number) => plural(n, 'product', 'products'),
    pricesAsOf: (d: string) => `Prices ${d}`,
    stockAsOf: (d: string) => `Stock as of ${d}`,
    updateReady: 'A new version of YQ Marketplace is ready.',
    refresh: 'Refresh',
    back: 'Back',
    close: 'Close',
    dismiss: 'Dismiss',
    /** the last-resort error screen (ui/ErrorBoundary) */
    errorTitle: 'Something went wrong',
    errorHint: 'The page hit an unexpected error. Reloading usually fixes it.',
    reload: 'Reload',
  },
} as const
